export const APP_ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  LOGIN: "/login",
  VERIFY: "/verify",
  HOW_WORKS: "/how",
  FAQ: "/faq",
  ABOUT: "/about",
  CONFIDENTIAL: "/politika",
  OFERTA: "/oferta",
  USLOVIYA: "/usloviya",
  RULE: "/rule",
  PAYMENT: "/payment",
  PROFILE: "/profile",
  CART: "/cart",
  MYESIM: "/myEsim",
  TARIFFS: "/tariffs/:id",
};
