export const APP_ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  LOGIN: "/login",
  VERIFY: "/verify",
  HOW_WORKS: "/how",
  FAQ: "/faq",
  ABOUT: "/about",
  CONFIDENTIAL: "/politika",
  OFERTA: "/oferta",
  USLOVIYA: "/usloviya",
  RULE: "/rule",
  PAYMENT: "/payment",
  THANK_YOU: "/thank-you",
  PROFILE: "/profile",
  CART: "/cart",
  MYESIM: "/myesim",
  TARIFFS: "/tariffs/:id",
  PRIVACY_POLICY: "/privacy-policy",
  PUBLIC_OFFER: "/public-offer",
  REFUND_POLICY: "/refund-policy",
};
