export const APP_ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  LOGIN: "/login",
  VERIFY: "/verify",
  HOW_WORKS: "/how",
  FAQ: "/faq",
  ABOUT: "/about",
  CONFIDENTIAL: "/politika",
  OFERTA: "/oferta",
  USLOVIYA: "/usloviya",
  RULE: "/rule",
  PAYMENT: "/payment",
  PROFILE: "/profile",
  PROFILE_PAGE: "/profile/profile",
  CART: "/profile/cart",
  ACTIVE: "/profile/active",
  INACTIVE: "/profile/inactive",
  HISTORY: "/profile/history",
  TARIFFS: "/tariffs/:id",
};
